controllers:
    resource: ../src/Controller/
    type: attribute

# index:
#    path: /
#    controller: App\Controller\DefaultController::index

# kernel:
#     resource: ../../src/Kernel.php
#     type: attribute